[[edge-functions]]
path = "/ims/*"
function = "ims-proxy"

[[edge-functions]]
path = "/api/*"
function = "ims-api"

[build]
  publish = "dist"
  command = "npm run build"
  edge_functions = "netlify/edge-functions"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
